### ISSUE TITLE
No Way to View Repo Test Status

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/java-docs-samples#1376]
## Issue

There is no way for me to see test status of this repo.
The "Build: Failing" badge does not link to the test status. It links to the image which is useless.

There's no other documentation to accessing the tests for this repo.

Please add a link to the tests such that an external user can view the status of the tests.

**Comment by kurtisvg** [comment]
Hey Grant --

Since we are using Kokoro, it's not possible to expose the results of our daily or continuous tests other than that badge. That badge gets updated every time Kokoro runs a continuous or periodic test.

For PRs, we use Resultstore, so it is possible to see the results of the tests for that sepcific PR by clicking the status links for the commit.
