### ISSUE TITLE
Update Sample Guidelines to recommend using exec:exec

### ISSUE THREAD

**Issue by kurtisvg** [GoogleCloudPlatform/java-docs-samples#1524]
See #1523 for example and reasoning

**Comment by lesv** [comment]
@gguuss FYI - since you appear to be solving this.

**Comment by gguuss** [comment]
Putting some notes here for edges so far:

# Multiple command utilities

If you have multiple command utilities to be executed by the Maven Plugin, specify them as a profile:

```XML
  <profiles>
    <profile>
      <id>mqtt</id>
      <activation>
        <property>
          <name>mqtt</name>
        </property>
      </activation>
    </profile>
  </profiles>
```

# Required named arguments

Required named arguments are specified within the <configuration>...<arguments>... section of the profiles section when you're using multiple execution runners.

The following example shows one style of specifying a required parameter

```XML
            <configuration>
              <executable>java</executable>
              <arguments>
                <argument>-classpath</argument>
                <classpath/>
                <argument>com.example.cloud.iot.examples.MqttExample</argument>
                <...>
                <argument>-project_id=${project_id}</argument>
                <...>
              </arguments>
            </configuration>
```

This parameter can be passed to the program as just the variable for exec to handle, for example, `-Dproject_id=NOUN-VERB-NUMBER`.

# Optional named arguments 

Because you don't want to specify optional named arguments unless they are passed, specify an argument where the variable alone is passed to the app.  

The following example shows how to pass an optional parameter:

```
            <configuration>
              <executable>java</executable>
              <arguments>
                <argument>-classpath</argument>
                <classpath/>
                <argument>com.example.cloud.iot.examples.MqttExample</argument>
                <...>
                <argument>${cr}</argument>
                <...>
              </arguments>
            </configuration>
```

This parameter is be passed to the program with its named parameter, for example, `-Dcd=cloud_region=us-central1`.

**Comment by gguuss** [comment]
* [Basic example POM.xml](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/firestore/pom.xml)
* [Complex example POM.xml](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/iot/api-client/manager/pom.xml)

**Comment by kurtisvg** [comment]
Closing this as I believe we decided we no longer want to use this pattern.
