### ISSUE TITLE
Broken Diagflow Tests

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#1533]
## In which file did you encounter the issue?

`/dialogflow/cloud-client/src/test/java/com/example/dialogflow/KnowledgeBaseManagementIT.java`
`dialogflow/cloud-client/src/test/java/com/example/dialogflow/SessionEntityTypeManagementIT.java`

## Describe the issue

[Test Fusion](https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/KOKORO/c3c8a9a4-b562-4f9b-8c97-d24d9ba1a042/1564945564751/build%20%23117/Targets?target=github%2Fjava-docs-samples%2Fdialogflow%2Fcloud-client%2Ftarget%2Ffailsafe-reports&drilldownTab=tests)

@nnegrey I know you've worked on improving the flakiness of these tests. These tests may be inherently flaky/broken.

**Comment by nnegrey** [comment]
Yea, I think it is time I talk to the product team about the Knowledge Base flakiness, it is still in beta, so that might be why we get random flakiness. If it isn't something that I can fix on my end, got any recommendations? 

However, I can definitely fix one of those bugs by using UUID display names like I've used in other cases since we now run 2 java versions at the same time.

**Comment by averikitsch** [comment]
I'll add it to our Java sync discussion topics.

**Comment by nnegrey** [comment]
Grrrrr. Someone deleted my knowledge base again that shouldn't have been deleted.

**Comment by nnegrey** [comment]
https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1535
