### ISSUE TITLE
DPEbot is not updating spring-cloud-gcp-dependencies

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#1651]
A few samples use:
```
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-gcp-dependencies</artifactId>
        <version>1.1.2.RELEASE</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```
In September, the version was updated to `1.1.3.RELEASE`, but DPEbot has not added this to the [PR](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1528/files)

**Comment by kurtisvg** [comment]
Looks like we've switch to Renvoate, so I'm going to mark this as closed.

**Comment by averikitsch** [comment]
Re-opening because Renovate hasn't picked up this dependency either.

**Comment by kurtisvg** [comment]
Renovate uses the `maven-versions-plugin` to run updates on these files. I tested the plugin manually and it seems to be working correctly and updating these bom versions.

I'm hoping that Renovate just hasn't gotten to this version yet since we've capped it to 5 prs at a time. I'll check back in a few weeks and see if it's updated.

**Comment by averikitsch** [comment]
Based on #1981 it looks like Renovate is picking this up now.
