### ISSUE TITLE
Problem connecting to Google Cloud PostgreSQL with the Servlet provided in the repo.

### ISSUE THREAD

**Issue by cesards** [GoogleCloudPlatform/java-docs-samples#2038]
I'm opening an issue because I spent most of my Sunday figuring out how to connect my Kotlin-based Backend (using Ktor) with the PostgreSQL DB instance in Google Cloud

** Preconditions **

I could connect to it by using gcloud from my shell (described [here](https://cloud.google.com/sql/docs/postgres/quickstart):
```
gcloud sql connect myinstance --user=postgres
```

After trying different URL combinations in order to connect to the Cloud DB through a JetBrains library called Exposed and failing to it, I followed the steps described in the [README](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/cloud-sql/postgres/servlet/README.md) of this repo and also [here](https://cloud.google.com/sql/docs/postgres/connect-app-engine)

Documentation and samples seem a little bit confusing, so I tried different combinations for setting the DB_NAME 

```
config.setJdbcUrl(String.format("jdbc:postgresql:///%s", DB_NAME));
config.setUsername(DB_USER); // e.g. "root", "postgres"
config.setPassword(DB_PASS); // e.g. "my-password"
```

I've tried connecting with IntelliJ, programmatically, and others. None of them work. URL combinations tried:
```
url = "jdbc:postgresql://{ip}/{PROJECT_ID:REGION:INSTANCE_ID}",
url = "jdbc:postgresql://{ip}",
url = "jdbc:postgresql://{PROJECT_ID:REGION:INSTANCE_ID}",
url = "jdbc:postgresql://{PROJECT_ID:REGION:INSTANCE_ID}=tcp:5432",
url = "jdbc:postgresql:{PROJECT_ID:REGION:INSTANCE_ID}",
url = "jdbc:postgresql:///{PROJECT_ID:REGION:INSTANCE_ID}",
// the last I tried was:
url = "jdbc:postgresql://{ip}:5432/{INSTANCE_ID}
```
None of them work. I'm a bit desperate to be honest.

I think [this is the line](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java#L49) that contains the wrong URL in order to connect to Google Cloud

**Comment by kurtisvg** [comment]
Hi cesards@,

That sample is using the [Cloud SQL JDBC Socket Factory](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#cloud-sql-socket-factory-for-jdbc-drivers). This library uses IAM credentials to authenticate connections to your Cloud SQL instance. 

In order for this to work, you have to do the following:
1. [Add the library as a dependency](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#postgresql). 
2. [Use your JDBC url to specify the `socketFactory` arg and the instanceName.](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#postgres)


In order to get this to work with the integrations in IntelliJ, you'll have to [follow these instructions to add a jar-with-deps alongside the driver](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#connect-with-intellij).
