### ISSUE TITLE
QuickstartArrowSample - the bigquery client appears not to be compatible w/ Java 11

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#2162]
## Describe the issue
```
java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available
	at com.example.bigquerystorage.QuickstartArrowSampleIT.testQuickstart(QuickstartArrowSampleIT.java:52)
```

**Comment by shollyman** [comment]
TODO: verify with Micah if this is a known issue in arrow, given other changes they're dealing with related to the arrow format.

**Comment by shollyman** [comment]
Looks like this surfaced for the arrow team itself here and became the doc guidance in https://issues.apache.org/jira/browse/ARROW-6206

tl;dr the ecommendation in that issue was to address netty issues by setting java option
-Dio.netty.tryReflectionSetAccessible=true

Under the hood grpc for java uses netty.
