### ISSUE TITLE
Publish `java-docs-samples/appengine-java11/appengine-simple-jetty- main

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/java-docs-samples#2294]
That is, avoid this annoyance in ~/java-docs-samples/appengine-java11/guestbook-cloud-firestore

```
    <!-- Dependency needs to be locally install from directory -->
		<!-- `java-docs-samples/appengine-java11/appengine-simple-jetty-
main' -->
		<!-- See the README for more information -->
    <dependency>
      <groupId>com.example.appengine.demo</groupId>
      <artifactId>simple-jetty-main</artifactId>
      <version>1</version>
      <scope>provided</scope>
    </dependency>
```

**Comment by averikitsch** [comment]
Unfortunately, we are not going to publish the simple jetty main artifact. This is due to lack of maintenance resources and not wanting users to think this is a production-ready server. We have provided the servlet example for Java 11 to show users how to migrate their servlets from the Java 8 runtime, but this is not the main way we see users running on Java 11 GAE.

**Comment by elharo** [comment]
Makes sense. Perhaps these two could be combined into a multimodule project so that it builds without extra steps? For samples, it's really nice to have very straightforward buildable units.

**Comment by averikitsch** [comment]
I have research options to improve the developer experience; however, due to the test setup we are unable to have multimodule projects in this repo.
