### ISSUE TITLE
SpannerSampleIT  Deadline_Exceeded

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#2571]
```
com.google.cloud.spanner.SpannerException: DEADLINE_EXCEEDED: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Deadline expired before operation could complete.
	at com.example.spanner.SpannerSampleIT.runSample(SpannerSampleIT.java:60)
	at com.example.spanner.SpannerSampleIT.testSample(SpannerSampleIT.java:268)
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Deadline expired before operation could complete.
```

**Comment by lesv** [comment]
Found in PR #2563

**Comment by skuruppu** [comment]
@olavloite, would you please be able to take a look? Thanks very much.

**Comment by olavloite** [comment]
I've seen similar flakes in other test cases as well, and the team developing the CPP client for Spanner is also running into a [similar issue](https://github.com/googleapis/google-cloud-cpp-spanner/issues/512). The problem is that the `CreateBackup` and `CreateDatabase` operations are non-idempotent. These can therefore sometimes fail with `DEADLINE_EXCEEDED` and/or `UNAVAILABLE` in case of temporary network problems or other transient issues.

I'll have a look and see if we can try to fix this in the client library by using approximately the following logic:
1. In case of a `DEADLINE_EXCEEDED` or `UNAVAILABLE` error for these `Create...` calls, the client library will query the backend for the corresponding long-running operation for the call.
1. If the long-running operation is found, the call will return an `OperationFuture` for the operation.
1. If the long-running operation was not found, the `Create...` call will be retried.
