### ISSUE TITLE
Spanner Samples updated to v6 com.google.cloud:libraries-bom

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#3182]
Found in #3179 [logs](https://source.cloud.google.com/results/invocations/ca8d20b2-1bb4-4ddd-b544-8e5581946b8b/targets/cloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava11%2Fpresubmit/log)

Looks like methods changed in a big way.

* appengine-java11/spanner
* functions/spanner
* spanner/cloud-client
* spanner/jdbc
* spanner/leaderboard/complete
* spanner/leaderboard/step4
* spanner/leaderboard/step5
* spanner/leaderboard/step6

@elharo FYI

**Comment by skuruppu** [comment]
These failures are surprising because we haven't removed any of these packages or methods that the logs say it can't find. So it's likely some issue with the dependency management.

Unfortunately, I don't really understand the dependency management setup we have. @olavloite would you please be able to take a look?

**Comment by olavloite** [comment]
This is the same problem as in #3139 and is caused by a missing dependency that should be included for all builds for Java 9 and higher. The base cause is https://github.com/mojohaus/flatten-maven-plugin/issues/145, and a workaround was added in https://github.com/googleapis/java-spanner/pull/261, but that is pending the release of Spanner client 1.55.2.

What does surprise me, however, is that this was not already picked up by the Samples test that are executed for each PR for the Spanner client. I'll add an issue to the Spanner repository to investigate why that is, to prevent this kind of error from happening again.

**Comment by lesv** [comment]
Thanks - It also fails in V7.  We are using the libraries-bom 5.4.0 and haven't updated since then due to this error.

**Comment by lesv** [comment]
@elharo @stephaniewang526 PTAL - The problem that @olavloite is talking about is that a bad client was released and put into the libraries-bom - the exact opposite of what we want - we probably want to figure out a process where when that happens, we signal the bom to revert the version so users aren't given bad things.

**Comment by olavloite** [comment]
The reason this did not fail the client library build is that the Spanner client library only tested the Samples using Java 8, while the dependency error that occurred was related to a dependency that should only be included in Java 9 and higher.

**Comment by skuruppu** [comment]
I'm trying to get https://github.com/googleapis/java-spanner/pull/259 merged which is v1.56.0 that has googleapis/java-spanner#261.

**Comment by skuruppu** [comment]
googleapis/java-spanner#259 is finally merged. Sorry for the delay.

**Comment by skuruppu** [comment]
It seems like this issue is still happening since I'm seeing the [same errors](https://source.cloud.google.com/results/invocations/dac4d567-7b5f-41ca-9618-a42d58082bac/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-spanner%2Fpresubmit%2Fsamples/log) in https://github.com/googleapis/java-spanner/pull/298.

**Comment by olavloite** [comment]
> It seems like this issue is still happening since I'm seeing the [same errors](https://source.cloud.google.com/results/invocations/dac4d567-7b5f-41ca-9618-a42d58082bac/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-spanner%2Fpresubmit%2Fsamples/log) in [googleapis/java-spanner#298](https://github.com/googleapis/java-spanner/pull/298).

It seems that Spanner 1.56.0 is not included in libraries-bom 7.0.2. libraries-bom 7.0.2 defines google.cloud.java.version 0.129.0, which again includes Spanner 1.55.1.

**Comment by suztomo** [comment]
I’m preparing Libraries-bom 8.0.0 that includes the latest google-cloud-bom.

**Comment by olavloite** [comment]
Thanks @suztomo 
libraries-bom 8.0.0 finally seems to fix this problem: https://github.com/googleapis/java-spanner/pull/307

**Comment by lesv** [comment]
Yep - thanks everyone!
