### ISSUE TITLE
TransferJobUtils.BASE_10 is weird and surprising

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/java-docs-samples#3706]
Remove it and use `Integer.parseInt` with no radix.

**Comment by kurtisvg** [comment]
Presumable this is referring to this file: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/76a8fa98620c25760d509376620cd3978b05ade9/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferJobUtils.java

There are a bunch of weird/incorrect things going on here:
1. Doesn't verify the string is in the proper format - could throw exceptions on array out of bounds
2. Calling "split" multiple times
3. Calls `system.Exit` instead of throwing an exception 

It's probably better to use `LocalTime` to parse the string instead.

**Comment by frankyn** [comment]
Thanks for raising this issue @elharo. @JesseLovelace is working on new samples for STS and wants to clean these samples up. I'll raise this issue to them when they're back from vacation.

**Comment by elharo** [comment]
FYI "Calls system.Exit instead of throwing an exception" is one of the reasons our static analysis CI build fails.
