### ISSUE TITLE
Spring Release Versions

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/java-docs-samples#4579]
Can we ask the dependency update bot to only use the RELEASE version for the samples in `pubsub/spring`?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/b865b4b7e0841a78c3fd1b73f552cf0cbb5016b2/pubsub/spring/pom.xml#L47-L53

See https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies. The latest RELEASE version should be `2.3.8.RELEASE` instead of `2.4.2`.

**Comment by lesv** [comment]
docs: https://docs.renovatebot.com/configuration-options/

**Comment by eaball35** [comment]
Fix didn't seem to work? https://github.com/GoogleCloudPlatform/java-docs-samples/pull/5508

**Comment by averikitsch** [comment]
This issue is out of date. The Spring framework does not use release any more and we do not use deps from [`org.springframework.cloud:spring-cloud-gcp-dependencies`](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-gcp-dependencies). We now use `com.google.cloud:spring-cloud-gcp-dependencies`. The pub/sub sample is up to date: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/61adbff0de2347edf352d9f611d938f6fb03d267/pubsub/spring/pom.xml#L55-L63
