### ISSUE TITLE
Can this be edited to use on Android?

### ISSUE THREAD

**Issue by Limoncool** [GoogleCloudPlatform/java-docs-samples#469]
I want to use Text Detection in an android app just like the sample of Mobile Label Detection app do, but change Label Detection to Text Detection. Can this sample be edited to be able to use in Android? Or just import some libraries? Thanks.

**Comment by tswast** [comment]
@Limoncool Yes, you should be able to use the text detection feature from the Android sample. See: https://github.com/GoogleCloudPlatform/cloud-vision/tree/master/android for the latest code for the Cloud Vision Android sample.

You will need to change the model used:
https://github.com/GoogleCloudPlatform/cloud-vision/blob/e07f7415d551d43c2507e82c1f2cc19d31dabd08/android/CloudVision/app/src/main/java/com/google/sample/cloudvision/MainActivity.java#L243
and then also change the response handling to get the text annotations instead of label annotations:
https://developers.google.com/resources/api-libraries/documentation/vision/v1/java/latest/com/google/api/services/vision/v1/model/AnnotateImageResponse.html#getTextAnnotations()

This is the library to use:
https://developers.google.com/api-client-library/java/apis/vision/v1
but I recommend downloading the whole cloud-vision sample since it also sets some headers to use API keys that are limited to your app.

**Comment by puneith** [comment]
@tswast What do you mean we should mention the Android sample? In the docs links?

**Comment by tswast** [comment]
I mean In the READMEs in this Java samples repo.

**Comment by puneith** [comment]
I am confused a bit. We have a separate repo for Android for NL. So, are you suggesting that we clarify in the README in this repo that there is a separate Android link?
