### ISSUE TITLE
Creating and Building Container Image for Dataflow Flex Template in Java

### ISSUE THREAD

**Issue by irvifa** [GoogleCloudPlatform/java-docs-samples#5038]
## Type
Feature request/Documentation

## In which file did you encounter the issue?

Dataflow Flex template Java. In the [documentation](https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates) it's possible to use custom Dockerfile to create the image for Python, however it's not mentioned for Java.

## Describe the issue

In the [documentation](https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates) it's possible to use custom Dockerfile to create the image for Python, however it's not mentioned for Java. Is it possible to create the same feature for Java as well, perhaps by providing a base image such as [distroless](https://github.com/GoogleContainerTools/distroless). Note that there's a page about [Configuring Flex Templates](https://cloud.google.com/dataflow/docs/guides/templates/configuring-flex-templates#java) where folks can define needed environment variable, however I'm not sure if there's more sample on how to use custom images for the template.

**Comment by davidcavazos** [comment]
Java automatically creates the Dockerfile for you, and we're in the process of updating that for Python as well so we can remove that step as well. This means that creating Flex Templates will no longer require creating a Dockerfile. Note that this Dockerfile is to _launch_ the Dataflow job, it is _not_ used for the Dataflow workers (a common source of confusion).

If you want to specify a custom image for the workers, you could use the `--workerHarnessContainerImage` flag ([defined here](https://beam.apache.org/releases/javadoc/2.28.0/index?org/apache/beam/runners/dataflow/options/DataflowPipelineWorkerPoolOptions.html)). You can read more about it in the [Using custom containers](https://cloud.google.com/dataflow/docs/guides/using-custom-containers), and [Container environments](https://beam.apache.org/documentation/runtime/environments) pages.

I don't think we have examples in Java showcasing this yet, but you can look at a [Python example here](https://cloud.google.com/dataflow/docs/samples/satellite-images-gpus) where we launch a Dataflow job using a custom Docker image for the workers. Note that this example does not base from the `apache/beam` image directly, but the only thing needed is that the image contains the worker launch files, which we [copy from the `apache/beam` image](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/cf464cfb54be4961eb94c6cd8aa517b497117cc8/dataflow/gpu-workers/Dockerfile#L28).

You can look at the available Java 11 images in [Docker Hub](https://hub.docker.com/r/apache/beam_java11_sdk/tags?page=1&ordering=last_updated).

I'll close this issue since we're planning to remove the Docker image step for Python as well, so it's working as expected. Please feel free to reach out if you have any other questions and I'll do my best to answer :)

**Comment by davidcavazos** [comment]
Java automatically creates the Dockerfile for you. We're currently in the process of doing the same for Python and removing the Dockerfile creation altogether. Note that the Docker image is used to _launch_ the Dataflow job, it is _not_ used for the workers.

You can "customize" the (internally generated) Dockerfile by setting some environment variables during the [`gcloud dataflow flex-template build`](https://cloud.google.com/sdk/gcloud/reference/beta/dataflow/flex-template/build) command, like `--env FLEX_TEMPLATE_JAVA_MAIN_CLASS="com.path.to.MyPipeline". You can look at more options at the [Configuring Flex Templates](https://cloud.google.com/dataflow/docs/guides/templates/configuring-flex-templates#java) page. But there's really not much customization in Java. As long as your pipeline compiles into a JAR file that contains all your dependencies, you only need to specify that.

If you want to use custom containers on the Dataflow workers, you would need to pass [`--workerHarnessContainerImage`](https://beam.apache.org/releases/javadoc/2.28.0/index?org/apache/beam/runners/dataflow/options/DataflowPipelineWorkerPoolOptions.html). You can look at the [Using custom containers in Dataflow](https://cloud.google.com/dataflow/docs/guides/using-custom-containers) and [Container environments](https://beam.apache.org/documentation/runtime/environments) pages for more information on this. I don't think we currently have a Java example for this, but here's a [Python example](https://cloud.google.com/dataflow/docs/samples/satellite-images-gpus) that uses a custom container for the workers.

I'm closing this for now since we'll remove the Docker image from the Python example as well in the future. Please feel free to reach out if you have any more questions :)

**Comment by irvifa** [comment]
HI @davidcavazos what I'm thinking is more like is it possible to add official documentation for [jib](https://github.com/GoogleContainerTools/jib) support to publish the dataflow flex template?

I understand that Dataflow Flex template is actually already supporting this, the example is provided on [this code](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/e4be77c435ddcb9f94f0e2ea184bd516a70517ca/v2/streaming-data-generator/pom.xml#L68-L84).

So is it possible to add this to the official documentation?

**Comment by davidcavazos** [comment]
I see, that would actually be a nice feature request for the Flex Templates team so jib support is enabled by default.

**Comment by davidcavazos** [comment]
@MelodyShen, do you think adding [jib](https://github.com/GoogleContainerTools/jib) support to Java Flex Templates would be feasible?

**Comment by irvifa** [comment]
Dataflow flex templates already have support for building via JIB. An example of where JIB is configured can be found [here](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/e4be77c435ddcb9f94f0e2ea184bd516a70517ca/v2/streaming-data-generator/pom.xml#L68-L84.)

Running a command such as : 

```
mvn clean package -Dimage=${TARGET_GCR_IMAGE} \
                  -Dbase-container-image=${BASE_CONTAINER_IMAGE} \
                  -Dbase-container-image.version=${BASE_CONTAINER_IMAGE_VERSION} \
                  -Dapp-root=${APP_ROOT} \
                  -Dcommand-spec=${COMMAND_SPEC} \
                  -am -pl ${TEMPLATE_MODULE}
```

is basically using jib to create the image and push to GCR (TARGET_GCR_IMAGE). Here's what works for my use case so far:

```
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>jib-maven-plugin</artifactId>
  <configuration>
    <from>
      <image>gcr.io/dataflow-templates-base/java11-template-launcher-base:20210120_RC00@sha256:0d1b2452c4bb8d2df4bbcc997658fc435cc19f55e6842ee21dbbf4760933bd1f</image>
    </from>
    <container>
      <entrypoint>INHERIT</entrypoint>
      <environment>
        <FLEX_TEMPLATE_JAVA_MAIN_CLASS>com.cexample.application.MainClass</FLEX_TEMPLATE_JAVA_MAIN_CLASS>
        <FLEX_TEMPLATE_JAVA_CLASSPATH>/app/resources:/app/classes:/app/libs/*</FLEX_TEMPLATE_JAVA_CLASSPATH>
      </environment>
    </container>
  </configuration>
</plugin>
```
