### ISSUE TITLE
Can't run app when add Cloud vision to gradle

### ISSUE THREAD

**Issue by thanhlv93** [GoogleCloudPlatform/java-docs-samples#552]
Hi all,
I have issus with google Cloud vision API , when i add to gradle then can't run app.
My gradle:
dependencies {
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:recyclerview-v7:25.0.1'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.android.support:design:25.0.1'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.android.support:cardview-v7:25.0.1'
    compile('com.google.cloud:google-cloud-translate:0.9.3-alpha') {
        exclude group: 'io.grpc', module: 'grpc-all'
        exclude group: 'com.google.protobuf', module: 'protobuf-java'
        exclude group: 'com.google.api-client', module: 'google-api-client-appengine'
    }
    compile('com.google.apis:google-api-services-translate:v2-rev47-1.22.0') {
        exclude group: 'com.google.guava'
    }
    compile 'com.google.api-client:google-api-client-android:1.20.0' exclude module: 'httpclient'
    compile group: 'com.google.cloud', name: 'google-cloud-vision', version: '0.9.3-alpha'
}

and I got a message :

Error:trouble processing "javax/transaction/HeuristicCommitException.class":
Error:Ill-advised or mistaken usage of a core class (java.* or javax.*)
Error:when not building a core library.
Error:This is often due to inadvertently including a core library file
Error:in your application's project, when using an IDE (such as
Error:Eclipse). If you are sure you're not intentionally defining a
Error:core class, then this is the most likely explanation of what's
Error:going on.
Error:However, you might actually be trying to define a class in a core
Error:namespace, the source of which you may have taken, for example,
Error:from a non-Android virtual machine project. This will most
Error:assuredly not work. At a minimum, it jeopardizes the
Error:compatibility of your app with future versions of the platform.
Error:It is also often of questionable legality.
Error:If you really intend to build a core library -- which is only
Error:appropriate as part of creating a full virtual machine
Error:distribution, as opposed to compiling an application -- then use
Error:the "--core-library" option to suppress this error message.
Error:If you go ahead and use "--core-library" but are in fact
Error:building an application, then be forewarned that your application
Error:will still fail to build or run, at some point. Please be
Error:prepared for angry customers who find, for example, that your
Error:application ceases to function once they upgrade their operating
Error:system. You will be to blame for this problem.
Error:If you are legitimately using some code that happens to be in a
Error:core package, then the easiest safe alternative you have is to
Error:repackage that code. That is, move the classes in question into
Error:your own package namespace. This means that they will never be in
Error:conflict with core system classes. JarJar is a tool that may help
Error:you in this endeavor. If you find that you cannot do this, then
Error:that is an indication that the path you are on will ultimately
Error:lead to pain, suffering, grief, and lamentation.
Error:1 error; aborting
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex '/Users/thanhlv10/.gradle/caches/modules-2/files-2.1/javax.transaction/transaction-api/1.1/2ca09f0b36ca7d71b762e14ea2ff09d5eac57558/transaction-api-1.1.jar' to '/Users/thanhlv10/Documents/Android/workspace/LeanVocabularyEnglish/app/build/intermediates/transforms/dex/debug/folders/1000/10/transaction-api-1.1_08247d5a5ad76d54ec97f25b2765cc9d2ddbcc67'

Plz tell me know if you have any solution.
Thanks

**Comment by gguuss** [comment]
Are you trying to do this from Android? I'm not currently testing from this 

You might want to try starting from the [Cloud vision sample](https://github.com/GoogleCloudPlatform/cloud-vision/tree/master/android/CloudVision).

**Comment by thanhlv93** [comment]
Yes, I tried Cloud vision Android sample and it's working but when I generate a APK , I got a message .

Error:Execution failed for task ':app:transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/common/annotations/Beta.class

I'm thinking "Cloud vision Android sample" and " com.google.cloud:google-cloud-translate:0.9.3-alpha " is Conflicts .

My gradle :
dependencies {
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:recyclerview-v7:25.0.1'
    compile 'com.android.support:design:25.0.1'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile('com.google.cloud:google-cloud-translate:0.9.3-alpha') {
        exclude group: 'io.grpc', module: 'grpc-all'
        exclude group: 'com.google.protobuf', module: 'protobuf-java'
        exclude group: 'com.google.api-client', module: 'google-api-client-appengine'
    }
    compile('com.google.apis:google-api-services-translate:v2-rev47-1.22.0') {
        exclude group: 'com.google.guava'
    }
    compile 'com.google.http-client:google-http-client-gson:1.22.0' exclude module: 'httpclient'
    compile 'com.google.apis:google-api-services-vision:v1-rev22-1.22.0'
    compile 'com.google.android.gms:play-services-ads:10.0.1'
    compile 'com.android.volley:volley:1.0.0'

}

**Comment by MuhammadMuzammilQadri** [comment]
Why is it not working with Cloud client library but with the android sample? All the documentation on Vision is about the client library.. I'm facing below error when adding 
dependency {
    compile "com.google.cloud:google-cloud-vision:0.9.4-beta"
}
in the project:

Error:trouble processing "javax/transaction/HeuristicCommitException.class":
Error:Ill-advised or mistaken usage of a core class (java.* or javax.*)
Error:when not building a core library.
Error:This is often due to inadvertently including a core library file
Error:in your application's project, when using an IDE (such as
Error:Eclipse). If you are sure you're not intentionally defining a
Error:core class, then this is the most likely explanation of what's
Error:going on.
Error:However, you might actually be trying to define a class in a core
Error:namespace, the source of which you may have taken, for example,
Error:from a non-Android virtual machine project. This will most
Error:assuredly not work. At a minimum, it jeopardizes the
Error:compatibility of your app with future versions of the platform.
Error:It is also often of questionable legality.
Error:If you really intend to build a core library -- which is only
Error:appropriate as part of creating a full virtual machine
Error:distribution, as opposed to compiling an application -- then use
Error:the "--core-library" option to suppress this error message.
Error:If you go ahead and use "--core-library" but are in fact
Error:building an application, then be forewarned that your application
Error:will still fail to build or run, at some point. Please be
Error:prepared for angry customers who find, for example, that your
Error:application ceases to function once they upgrade their operating
Error:system. You will be to blame for this problem.
Error:If you are legitimately using some code that happens to be in a
Error:core package, then the easiest safe alternative you have is to
Error:repackage that code. That is, move the classes in question into
Error:your own package namespace. This means that they will never be in
Error:conflict with core system classes. JarJar is a tool that may help
Error:you in this endeavor. If you find that you cannot do this, then
Error:that is an indication that the path you are on will ultimately
Error:lead to pain, suffering, grief, and lamentation.
Error:1 error; aborting
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

**Comment by gguuss** [comment]
I'm currently not testing the Cloud Client library approach with Android. I'll see if I can come up with a working solution for you.

**Comment by gguuss** [comment]
I was able to get the project to build [using JarJar](https://github.com/vRallev/jarjar-gradle) as described in the error.

**Comment by thanhlv93** [comment]
@gguuss Could you explain my error ?

**Comment by gguuss** [comment]
Your error is occurring because the Cloud library has dependencies that conflict with core Android services. Even if you get past the error, you will need to figure out a way to authorize the library by building a custom credential object because the Cloud library is tightly coupled to default application credentials.

The Cloud client libraries are not intended to be used on Android, which is why there is a separate vision library for Android.

**Comment by thanhlv93** [comment]
Thank you for your answer , so i understood that now we have no Cloud client for Android and waiting when Google provide a version for android ?

**Comment by gguuss** [comment]
@thanhlv93 Correct, the Cloud client library does not explicitly support Android but it does work from Gradle. If I come up with a solution to authenticating the client library on Android, I'll be sure to share it. If you can get it to work, please let us know!

**Comment by thanhlv93** [comment]
@gguuss ok , I got it. Thanks

**Comment by nnegrey** [comment]
This appears to have been resolved. Please feel free to reopen if this is not true. :)
