### ISSUE TITLE
DEADLINE_EXCEEDED error while running the Recognize.java file from cloud speech java-docs-samples

### ISSUE THREAD

**Issue by shuchishah** [GoogleCloudPlatform/java-docs-samples#565]
## In which file did you encounter the issue?

Speech\cloud\src\main\java\com\example\speech\Recognize.java

### Did you change the file? If so, how?

No

## Describe the issue

![image](https://cloud.githubusercontent.com/assets/18505359/23996015/f36552c2-0a71-11e7-9932-d17cda755fd1.png)

**Comment by gguuss** [comment]
@shuchishah Please provide more information about what's going on:

- Are you using a GCS path? Can you gcsutil ls the path you're processing?
- Have you setup your application as described (in better detail) in [the GRPC example](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/speech/grpc)?
- Have you tried 

Also, can you try running the QuickStart sample:
```
cd speech/cloud-client/ && mvn clean package -DskipTests
mvn exec:java -Dexec.mainClass=com.example.speech.QuickstartSample
```

**Comment by shuchishah** [comment]
I have tried for GCS path as well as for local file path.
I have also tried QuickstartSample but it is giving the same error.
I have created a maven application and added gRPC dependancies.  
I have these pom.xml file which adds the gRPC 1.0.3 dependancy.
![image](https://cloud.githubusercontent.com/assets/18505359/24488412/51958db8-1534-11e7-9342-0f8cbc23bd58.png)

**Comment by gguuss** [comment]
@shuchishah The most common issue with this is authentication, have you run [`gcloud auth application-default login`](https://cloud.google.com/sdk/gcloud/reference/beta/auth/application-default/login) and set your project configuration to a project with the Speech API enabled?

**Comment by shuchishah** [comment]
I have already set the application credentials and Speech API is also enabled.

**Comment by gguuss** [comment]
When you run `gcloud auth application-default print-access-token` does it show a valid token? You can [check the token using the API explorer](https://developers.google.com/apis-explorer/#p/oauth2/v2/oauth2.tokeninfo).

**Comment by gguuss** [comment]
One more thing worth checking: 

Is your sample_rate (or sample_rate_hertz) set to the correct value for your audio? 

If you're setting the value **lower** than your actual recorded sample rate, the API will assume that several times the actual recoded length of audio needs to be processed and will take abnormally long to process requests.

**Comment by shuchishah** [comment]
Yes, I have checked sample_rate of audio.The same audio is working perfectly with python environment.

**Comment by gguuss** [comment]
The version of Speech you're using is outdated. Please use the following configuration in `pom.xml`:

    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-speech</artifactId>
      <version>0.17.1-alpha</version>
    </dependency>
    <dependency>
      <groupId>com.google.api</groupId>
      <artifactId>gax</artifactId>
      <version>1.0.0</version>
      <exclusions>
        <exclusion> 
          <groupId>com.google.guava</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.google.api</groupId>
      <artifactId>gax-grpc</artifactId>
      <version>0.16.0</version>
      <exclusions>
        <exclusion> 
          <groupId>com.google.guava</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

You will need to make a few changes to make your code similar to those [in this PR](https://github.com/GoogleCloudPlatform/java-docs-samples/commit/dfb4142be432655fffccd60233eda49f336e3d0e). It may also be useful for you to try starting from [the Speech Java sample](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/speech/cloud-client) as there could be other changes I'm forgetting about since 0.10.0.

**Comment by nnegrey** [comment]
This appears to have been resolved. Please feel free to reopen if this is not true. :)

**Comment by usmanQNL** [comment]
I am getting the same error DEADLINE EXCEEDED. Here is a snippet of the Eror. I am running the code without any change from your example(s).

`Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.texttospeech.v1.TextToSpeechClient.synthesizeSpeech(TextToSpeechClient.java:268)
		at com.google.cloud.texttospeech.v1.TextToSpeechClient.synthesizeSpeech(TextToSpeechClient.java:241)
		at com.gcp.cloudfunctions.CloudTextToSpeech.toSpeech(CloudTextToSpeech.java:78)
		at com.gcp.cloudfunctions.TestMain.main(TestMain.java:181)
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 19.943840244s. [buffered_nanos=1336808751, buffered_nanos=18610183072, waiting_for_connection]`


 I tried running it from CloudFunction but I get the same error there. The offending line (while debugging) seems to be this one.

`SynthesizeSpeechResponse response =
          textToSpeechClient.synthesizeSpeech(input, voice, audioConfig);`

Any advice?
