### ISSUE TITLE
Code snippet error - response.getResult returns nullptr if job not completed.

### ISSUE THREAD

**Issue by cobookman** [GoogleCloudPlatform/java-docs-samples#570]
# In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/bigquery/cloud-client/src/main/java/com/example/bigquery/SimpleApp.java#L53

### Did you change the file? If so, how?

 ```QueryResponse response = bigquery.query(queryRequest);
 while (!response.jobCompleted()) {
   Thread.sleep(1000);
   response = bigquery.getQueryResults(response.getJobId());
 }
 List<BigQueryError> executionErrors = response.getExecutionErrors();
 // look for errors in executionErrors
 QueryResult result = response.getResult();
```

## Describe the issue

`response.getResult()` will return with a nullptr if the job has not completed yet. It does not block until job is completed.

http://googlecloudplatform.github.io/google-cloud-java/0.5.0/apidocs/com/google/cloud/bigquery/QueryResponse.html#getResult()

**Comment by lesv** [comment]
@tswast PTAL

**Comment by tswast** [comment]
The behavior of the `.query()` method is confusing since it can sometimes return results, and sometimes you have to poll as you describe.

You're correct that we should always poll in the samples since that is likely to be needed. I'll update this one today.

Related: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1588 I've proposed to the client library team that we don't use `.query()` without an explicit JobID anywhere.
