### ISSUE TITLE
Error in publishing message using the MQTT client.

### ISSUE THREAD

**Issue by testover99** [GoogleCloudPlatform/java-docs-samples#887]
## In which file did you encounter the issue?

java-docs-samples/iot/api-client/mqtt_example/src/main/java/com/google/cloud/iot/examples/MqttExample.java

On publishing the payload at line 168 in MqttExample.java class, paho client is giving the following error:

I believe my parameters are correct as if I update the configuration of the device from the console, I receive on my MQTT client. 

```
Exception in thread "main" Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(Unknown Source)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 more
```

**Comment by lesv** [comment]
Gus is out today, hopefully he can address this Monday - it looks like you are ok at the moment.

**Comment by gguuss** [comment]
@testover99 is this happening on every request or is this happening after 60 minutes-ish?

**Comment by testover99** [comment]
No, not at 60 seconds, it is happening as soon as the client.publish(mqttTopic, message); is called.

**Comment by testover99** [comment]
Any updates on this. I am still trying to get this error resolved but not found anything yet.

**Comment by lesv** [comment]
@nnegrey PTAL

**Comment by nnegrey** [comment]
@testover99, how are you invoking the example?

**Comment by gguuss** [comment]
@testover99 I just got back from leave, in most cases where you see issues such as this, a device wasn't registered correctly, or the auth credentials are incorrect. It sounds like this is __not__ the case for you because you're able to subscribe to the configuration topic and receive updates, you just cannot publish telemetry data.

The most likely cause for this is that the topic you're publishing to is incorrect.  A device may publish only to an MQTT topic that starts with:

    /devices/{device-id}/events

Are you publishing to the correct topic for your device?

**Comment by nnegrey** [comment]
Closing this issue as there has been no followup. Please feel free to reopen the issue. :)
