### ISSUE TITLE
URL to install Java is broken/invalid in README.md files

### ISSUE THREAD

**Issue by kelumkps** [GoogleCloudPlatform/java-docs-samples#978]
## Describe the issue

In below two README.md files, the URL specified to install **Java** is invalid. The colon character is missing in the URL of both files. Therefore, the hyper link is pointing incorrectly to **Github** itself.

## In which file did you encounter the issue?

* storage/xml-api/cmdline-sample/README.md (line no: 29)

```
* Install the latest version of [Java](http//java.com) and
```

* storage/xml-api/serviceaccount-appengine-sample/README.md   (line no: 18)

```
**Prerequisites:** install the latest version of [Java](http//java.com) and
```

### Did you change the file? If so, how?
* storage/xml-api/cmdline-sample (line no: 29)

```
* Install the latest version of [Java](http://java.com) and
```

* storage/xml-api/serviceaccount-appengine-sample/README.md   (line no: 18)

```
**Prerequisites:** install the latest version of [Java](http://java.com) and
```

Shall I submit a pull request with the fix as a patch?

**Comment by kurtisvg** [comment]
Hey @kelumkps, thanks for bringing this issue to our attention. Because this issue only required a minor correction, I went ahead and just fixed it in commit 6fc6424c9523c1be70d24b96bed660c3ad38a0fe. 

If you find any more issues in the future you want to fix, we are happy to evaluate and accept PRs. Thanks!
